package HW.Methods;

public class MethodsHomework2 {
    /*

    1-create one method which is -->> EvenOddNums
this method will accept one parameter which is String
In this String there will be 10 digit numbers like 1234567890
Take the each digit from the number and if the digit is an even number add the digits,
if the digit is an odd number subtract the digits.
Print the total.
For example
String is "6678421312"
6 + 6 - 7 + 8 + 4 + 2 - 1 - 3 - 1 + 2
result should be 16

2-Create one method name is -->> findTheDifference
Accepts two Strings
Returns the char
Given two strings s and String t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
```
Input:
s = "abcde"
t = "abcd"
Output: e
Explanation: 'e' is the letter that was added.
```
```
s = "qawer"
t = "rewq"
Output: a
Explanation: 'a' is the letter that was added.
```
3-Create one method name is removeDuplicate
Which accepts int array
You are expected to remove the duplicated elements in the array and
 return the length of the  array which doesn't include the duplicated ones.
Return type will be integer.
Example 1:
```
Given nums = [1,1,2],
Your function should return length = `2`, with the first two elements of nums being `1` and `2` respectively.
```
Example 2:
```
Given nums = [0,0,1,1,1,2,2,3,3,4],
Your function should return length = `5`, with the first five elements of nums being modified to `0`, `1`, `2`, `3```

4-Create one method name is  addDigits
Taking int as a parameter.
 Return type is also int
Given a positive integer `num`, repeatedly add all its digits until the result has only one digit.
**Example:**
```
Input: `38`
Output: 2
Explanation: The process is like: `3 + 8 = 11`, `1 + 1 = 2`.
             Since `2` has only one digit, return it.
```

5-Create method -->> isPalindrome
Method accept one String as a parameter
Return type should be boolean
Verify String is a palindrome or not
Palindrome is  -->>  A **palindrome** is a word, phrase, or sentence reads the same backward or forward.
Given a String, determine if it is a palindrome.
Example 1:
Input: "Java"
Output: false
```
`, and `4` respectively.
Example 2:
Input: "Madam"
Output: true
```



     */
}
